tut_01/urls.py
from django.contrib import admin
from django.urls import path
from boards import views

urlpatterns = [
    path('', views.home, name="home"),
    path('boards/<int:pk>/', views.board_topics, name="board_topics"),
    path('boards/<int:pk>/new/', views.new_topic, name="new_topic"),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.CASCADE)

boards/forms.py
from django import forms
from .models import Topic

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?', 'class': 'form-control'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )

    subject = forms.CharField(
        widget = forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = Topic
        fields = ['subject', 'message']

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.http import HttpResponse
from django.http import Http404
from .models import Board, User, Topic, Post
from .forms import NewTopicForm

# Create your views here.
def home(request):
    # return HttpResponse('Hello, World!')
    # boards = Board.objects.all()
    # boards_names = list()

    # for board in boards:
    #     boards_names.append(board.name)

    # response_html =  '<br>'.join(boards_names)
    # return HttpResponse(response_html)

    boards = Board.objects.all()
    return render(request, 'home.html', {'boards': boards})

def board_topics(request, pk):
    # option 1
    # board = Board.objects.get(pk=pk)
    # return render(request, 'topics.html', {'board': board})

    # option 2
    # try:
    #     board = Board.objects.get(pk=pk)
    # except Board.DoesNotExist:
    #     raise Http404
    # return render(request, 'topics.html', {'board': board})

    board = get_object_or_404(Board, pk=pk)
    return render(request, 'topics.html', {'board': board})

def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    user = User.objects.first()

    if request.method == 'POST':
        # option 1: before using NewTopicForm
        # subject = request.POST['subject']
        # message = request.POST['message']

        # # TODO: get the currently logged in user
        # user = User.objects.first()

        # topic = Topic.objects.create(
        #     subject=subject,
        #     board=board,
        #     starter=user
        # )

        # post = Post.objects.create(
        #     message=message,
        #     topic=topic,
        #     created_by=user
        # )

        # # TODO: redirected to the created topic page
        # return redirect('board_topics', pk=board.pk)

        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()

            post = Post.objects.create(
                message = form.cleaned_data.get('message'),
                topic = topic,
                created_by = user
            )

            return redirect('board_topics', pk=board.pk)
    else:
        form = NewTopicForm()
    return render(request, 'new_topic.html', {'board': board, 'form': form})

boards/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %} Django Boards {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}"> Django Boards</a>
        </div>
    </nav>
    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}
            {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

boards/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
   <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

boards/templates/home_v1.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Boards</title>
  </head>
  <body>
    <h1>Boards</h1>

    {% for board in boards %}
      {{ board.name }} <br>
    {% endfor %}

  </body>
</html>

boards/templates/home_v2.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Boards</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
  </head>
  <body>
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">Boards</li>
      </ol>
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">0</td>
              <td class="align-middle">0</td>
              <td></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>

boards/templates/includes/form.html
<!-- option 2: using django's form -->
<!-- {{ form.as_p }} -->

{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                <!-- need to add class is-invalid -->
                {{ field }}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor%}
            {% else %}
                <!-- need to add class is-valid -->
                {{ field }}
            {% endif %}
        {% else %}
            {{ field }}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}

boards/templates/new_topic.html
{% extends 'base.html' %}

{% block title %} Start a New Topic {% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'home' %}">Boards</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
    </li>
    <li class="breadcrumb-item active">New Topic</li>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <!-- option 1: before using django's form -->
        <!-- <div class="form-group">
            <label for="id_subject">Subject</label>
            <input type="text" name="subject" id="subject" class="form-control">
        </div>

        <div class="form-group">
            <label for="id_message">Message</label>
            <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
        </div> -->



        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Post</button>
    </form>
{% endblock %}

boards/templates/topics.html
{% extends 'base.html' %}

{% block title%}
    {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'home' %}">Boards</a>
    </li>
    <li class="breadcrumb-item active">
        {{board.name}}
    </li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New Topic</a>
    </div>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Topic</th>
                <th>Starter</th>
                <th>Replies</th>
                <th>Views</th>
                <th>Last Update</th>
            </tr>
        </thead>
        <tbody>
            <!--  inside python code, we have to use parenthesis: board.topics.all() -->
            <!-- but in HTML template, we don't use parenthesis -->
            {% for topic in board.topics.all %}
                <tr>
                    <td>{{ topic.subject }}</td>
                    <td>{{ topic.starter.username }}</td>
                    <td>0</td>
                    <td>0</td>
                    <td>{{ topic.last_updated }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

boards/templates/topics_v1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{board.name}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item">
                <a href="{% url 'home' %}">Boards</a>
            </li>
            <li class="breadcrumb-item active">
                {{board.name}}
            </li>
        </ol>
    </div>
</body>
</html>